const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Timer,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Behaviors.scrollto,
		C3.Plugins.Browser,
		C3.Plugins.Arr,
		C3.Behaviors.Pin,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Json,
		C3.Plugins.Dictionary,
		C3.Behaviors.destroy,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.AJAX,
		C3.Plugins.Internationalization,
		C3.Behaviors.Fade,
		C3.Plugins.LocalStorage,
		C3.Plugins.TextBox,
		C3.Plugins.Clipboard,
		C3.Plugins.NinePatch,
		C3.Plugins.CSV,
		C3.Plugins.skymen_pokiSDK,
		C3.Plugins.PlatformInfo,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.CSV.Acts.ParseCSV,
		C3.Plugins.AJAX.Exps.LastData,
		C3.JavaScriptInEvents.EventSheet1_Event53_Act3,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Plugins.System.Cnds.IsNaN,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.layerindex,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Acts.Signal,
		C3.Behaviors.Physics.Exps.AngularVelocity,
		C3.Behaviors.Physics.Acts.ApplyTorque,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Behaviors.Physics.Acts.CreateDistanceJoint,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Behaviors.Physics.Acts.CreatePrismaticJoint,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Behaviors.Physics.Acts.CreateLimitedRevoluteJoint,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Particles.Exps.Count,
		C3.Plugins.Particles.Acts.SetY,
		C3.Plugins.Particles.Exps.Y,
		C3.Behaviors.Physics.Cnds.CompareAngularVelocity,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Behaviors.Physics.Acts.RemoveJoints,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.HasParent,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.System.Exps.time,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetInitSpeed,
		C3.Plugins.Particles.Acts.SetParticleAcc,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Arr.Acts.Push,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Plugins.TiledBg.Acts.MoveToLayer,
		C3.Behaviors.Physics.Exps.Friction,
		C3.Behaviors.Physics.Acts.SetFriction,
		C3.Plugins.TiledBg.Acts.SetImageAngle,
		C3.Plugins.TiledBg.Exps.ImageAngle,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Physics.Acts.ApplyImpulseToward,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.TiledBg.Exps.Angle,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Behaviors.Physics.Exps.Elasticity,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.TiledBg.Exps.Count,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Sin.Exps.Value,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Physics.Exps.Mass,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.AccelerationX,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.Touch.Exps.YAt,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.TiledBg.Acts.SetImageScaleX,
		C3.Plugins.TiledBg.Acts.SetImageScaleY,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.TiledBg.Cnds.PickByUID,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Sprite.Exps.BBoxMidX,
		C3.Plugins.Sprite.Exps.BBoxMidY,
		C3.Plugins.Sprite.Exps.ZIndex,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.TiledBg.Exps.BBoxMidX,
		C3.Plugins.TiledBg.Exps.BBoxMidY,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Exps.ZIndex,
		C3.Plugins.TiledBg.Exps.UID,
		C3.Plugins.TiledBg.Exps.LayerName,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.TiledBg.Exps.ObjectTypeName,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Exps.tickcount,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Exps.log10,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnError,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.System.Acts.AddLayer,
		C3.Plugins.System.Acts.RemoveLayer,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Spritefont2.Exps.Tags,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetLayerForceOwnTexture,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Acts.SetPos,
		C3.Plugins.TextBox.Exps.Width,
		C3.Plugins.TextBox.Acts.SetWidth,
		C3.Plugins.TextBox.Exps.BBoxRight,
		C3.Plugins.System.Exps.trim,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.System.Exps.roundtodp,
		C3.Plugins.Clipboard.Acts.CopyText,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Spritefont2.Acts.SetSize,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.skymen_pokiSDK.Acts.Interstitial,
		C3.Plugins.skymen_pokiSDK.Acts.Rewarded,
		C3.Plugins.skymen_pokiSDK.Cnds.OnIntertsitialComplete,
		C3.Plugins.skymen_pokiSDK.Cnds.OnRewardedComplete,
		C3.Plugins.skymen_pokiSDK.Cnds.LastRewardedSuccess,
		C3.Plugins.skymen_pokiSDK.Acts.GameplayStop,
		C3.Plugins.skymen_pokiSDK.Acts.GameplayStart,
		C3.Plugins.skymen_pokiSDK.Acts.LoadingEnd,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.JavaScriptInEvents.EventSheet1_Event1663_Act1,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Particles.Exps.Angle
	];
};
self.C3_JsPropNameTable = [
	{id: 0},
	{triggered: 0},
	{idd: 0},
	{value: 0},
	{resize_type: 0},
	{can_kill: 0},
	{pl: 0},
	{pl_c: 0},
	{pl_t: 0},
	{Physics: 0},
	{Tween: 0},
	{finish: 0},
	{wheel_elastic: 0},
	{wheel_friction: 0},
	{slis: 0},
	{space: 0},
	{spd_bst: 0},
	{is_triggered: 0},
	{is_first_pressed: 0},
	{in_game_button: 0},
	{text_id: 0},
	{trigger_zone: 0},
	{ice: 0},
	{batut: 0},
	{is_white_theme: 0},
	{upper_than_platforms: 0},
	{strelka: 0},
	{checkpoint: 0},
	{physics_stabilize: 0},
	{saved_angle: 0},
	{Timer: 0},
	{mn: 0},
	{spk: 0},
	{block_fire: 0},
	{is_loaded: 0},
	{is_loading: 0},
	{cant_shoot: 0},
	{bow: 0},
	{roll_s: 0},
	{is_working: 0},
	{Sine: 0},
	{saw: 0},
	{bike: 0},
	{damaged: 0},
	{is_on_ice: 0},
	{wheel: 0},
	{Keyboard: 0},
	{Touch: 0},
	{zoom: 0},
	{cur_zum: 0},
	{orientation_value: 0},
	{ScrollTo: 0},
	{Sine2: 0},
	{camera: 0},
	{connector: 0},
	{Browser: 0},
	{sitelock: 0},
	{head: 0},
	{leg: 0},
	{body_top: 0},
	{arm_: 0},
	{arm: 0},
	{leg_: 0},
	{is_wheel_joint: 0},
	{Pin: 0},
	{joint_to_bike_point: 0},
	{Particles_wheel: 0},
	{Particles_head: 0},
	{test_text: 0},
	{fon1: 0},
	{top_button: 0},
	{player_spawner: 0},
	{editor_corner_changer: 0},
	{Mouse: 0},
	{map_data: 0},
	{JSON: 0},
	{editor_obj_saver: 0},
	{editor_selecor: 0},
	{editor_angle_changer: 0},
	{w_to_h: 0},
	{editor_menu_fon: 0},
	{build_menu_box: 0},
	{editor_obj_ava: 0},
	{editor_trash: 0},
	{editor_menu_buttons: 0},
	{is_stuck: 0},
	{lifetime: 0},
	{DestroyOutsideLayout: 0},
	{arrow: 0},
	{particles_explosion: 0},
	{particles_explosion_smoke: 0},
	{Audio: 0},
	{raycast: 0},
	{sound_pool: 0},
	{hat: 0},
	{map_ava: 0},
	{confetty: 0},
	{particles_confetty: 0},
	{is_pressed: 0},
	{touch_id: 0},
	{mobile_control_buttons: 0},
	{button: 0},
	{text_key: 0},
	{text: 0},
	{side: 0},
	{editor_side_changer: 0},
	{editor_menu_page: 0},
	{editor_menu_page_logos: 0},
	{Vertical: 0},
	{scroll_max_speed: 0},
	{auto_scrolling: 0},
	{auto_scrolling_speed: 0},
	{auto_scrolling_angle: 0},
	{scrolling: 0},
	{scroll_offset: 0},
	{editor_menu_listat: 0},
	{localization: 0},
	{AJAX: 0},
	{Internationalization: 0},
	{Fade: 0},
	{color_rect: 0},
	{pers_logo: 0},
	{tutor_buttons: 0},
	{loading_sprite: 0},
	{pause_fon: 0},
	{pause_buttons: 0},
	{pause_levels_asset: 0},
	{w_h_coef: 0},
	{listatt: 0},
	{opened_levels: 0},
	{LocalStorage: 0},
	{save_data: 0},
	{TextInput: 0},
	{Clipboard: 0},
	{kb_enter: 0},
	{my_maps_button: 0},
	{my_maps_listat: 0},
	{origin_in_start_side: 0},
	{scroll_limit_a: 0},
	{scroll_limit_b: 0},
	{listat: 0},
	{my_maps: 0},
	{message: 0},
	{"9patch": 0},
	{CSV: 0},
	{PokiSDK: 0},
	{bike_fixing_bug: 0},
	{particles_confetty_flag: 0},
	{PlatformInfo: 0},
	{tutor_hand: 0},
	{road_ui: 0},
	{road_ui_head: 0},
	{autoflip_zone: 0},
	{body: 0},
	{kill_zones: 0},
	{player: 0},
	{platforms: 0},
	{level_obj: 0},
	{level_obj_tiled: 0},
	{editor_menu: 0},
	{listats: 0},
	{fons: 0},
	{loading_spr: 0},
	{menu_buttons: 0},
	{pause_level_asset_clone: 0},
	{checkpointt: 0},
	{is_dead: 0},
	{stage: 0},
	{level: 0},
	{health: 0},
	{is_bike_mirrored: 0},
	{language: 0},
	{attempt_count: 0},
	{total_deaths: 0},
	{layout_time: 0},
	{is_other_level_started_now: 0},
	{siz: 0},
	{block: 0},
	{stop_speed: 0},
	{speed: 0},
	{cur_language_index: 0},
	{localization_load_attempts: 0},
	{lang: 0},
	{y: 0},
	{key: 0},
	{index: 0},
	{start_mobile_zoom: 0},
	{speed_to_change_camera_speed: 0},
	{camera_smooth_offset: 0},
	{target_dir: 0},
	{base_val: 0},
	{vel_to_change_dir: 0},
	{sens: 0},
	{temp_max_zoom: 0},
	{temp_min_zoom: 0},
	{offset: 0},
	{num: 0},
	{prev_level_name: 0},
	{bike_rotating_towards: 0},
	{bike_move_acceleration: 0},
	{bike_max_speed: 0},
	{bike_max_angular_velocity: 0},
	{bike_move_direction: 0},
	{bike_rotate_speed: 0},
	{bike_rotate_direction: 0},
	{bike_local_vel_x: 0},
	{bike_local_vel_y: 0},
	{last_level: 0},
	{localizaton_loaded: 0},
	{cur_bike_rotate_speed: 0},
	{wheel_move_limit: 0},
	{wheel_damping: 0},
	{wheel_spring: 0},
	{bike_x: 0},
	{bike_y: 0},
	{bike_vel_x: 0},
	{bike_vel_y: 0},
	{bike_ang_vel: 0},
	{mirror: 0},
	{wheel_id: 0},
	{damage_distance: 0},
	{force: 0},
	{body_move_force: 0},
	{body_last_hit_time: 0},
	{min_volume: 0},
	{max_volume: 0},
	{lowes_velocity_for_min_volume: 0},
	{velocity_for_max_volume: 0},
	{is_outside_of_layout: 0},
	{kill: 0},
	{game_over_wait_block: 0},
	{is_finished: 0},
	{h: 0},
	{level_name: 0},
	{next_level: 0},
	{next_stage: 0},
	{default_friction: 0},
	{ice_friction: 0},
	{mine_force: 0},
	{max_distance: 0},
	{arrow_force: 0},
	{bow_distance: 0},
	{max_ang_vel: 0},
	{decceleration: 0},
	{poki_pill_offset: 0},
	{size: 0},
	{press_opacity: 0},
	{norm_opacity: 0},
	{tutor_block_rotate: 0},
	{tutor_block_front_and_back: 0},
	{tutor_anti_fall: 0},
	{s1_max_level: 0},
	{color_index: 0},
	{start_h: 0},
	{c: 0},
	{hp: 0},
	{x: 0},
	{m: 0},
	{r1: 0},
	{g1: 0},
	{b1: 0},
	{R: 0},
	{G: 0},
	{B: 0},
	{s: 0},
	{l: 0},
	{level_step: 0},
	{timeee: 0},
	{dif: 0},
	{dist: 0},
	{sp: 0},
	{timee: 0},
	{spike_pos_offset: 0},
	{tutor_sine_old_value_1: 0},
	{button_active_opacity: 0},
	{button_norm_opacity: 0},
	{hand_spawned: 0},
	{gravity_left_right: 0},
	{left_right: 0},
	{gr: 0},
	{ang: 0},
	{is_editing_mode: 0},
	{editor_obj_count: 0},
	{current_map_index: 0},
	{current_map_name: 0},
	{editor_zoom: 0},
	{name_exist: 0},
	{map_name: 0},
	{b_offset: 0},
	{is_camera_moving: 0},
	{prevX: 0},
	{prevY: 0},
	{ScrollSpeed: 0},
	{direction: 0},
	{min_zoom: 0},
	{max_zoom: 0},
	{initialZoomDistance: 0},
	{curZumDistance: 0},
	{initialZoom: 0},
	{scale: 0},
	{editor_selected_obj_uid: 0},
	{pos_offset: 0},
	{uid: 0},
	{editor_grid_size: 0},
	{temp_max_z: 0},
	{temp_best_uid: 0},
	{uid_to_select: 0},
	{editor_dragging_corner_uid: 0},
	{anchor_x: 0},
	{anchor_y: 0},
	{anchor_corner_id: 0},
	{editor_w_offset: 0},
	{editor_h_offset: 0},
	{new_w: 0},
	{new_h: 0},
	{editor_angle_changing: 0},
	{editor_angle_offset: 0},
	{step: 0},
	{editor_dragging_side_uid: 0},
	{f_dist: 0},
	{final_size: 0},
	{editor_is_dragging_obj: 0},
	{editor_drag_off_x: 0},
	{editor_drag_off_y: 0},
	{offset_x: 0},
	{offset_y: 0},
	{acceleration: 0},
	{max_speed: 0},
	{editor_menu_opened: 0},
	{editor_menu_hidden: 0},
	{max_w: 0},
	{editor_menu_touch_start_x: 0},
	{editor_menu_touch_start_y: 0},
	{editor_menu_pending_uid: 0},
	{editor_menu_obj_dragging: 0},
	{is_sound: 0},
	{already_play_count: 0},
	{sound_unique_tag: 0},
	{sound_name: 0},
	{tag: 0},
	{volume: 0},
	{pitch: 0},
	{max_sounds: 0},
	{eng_last_active_tick: 0},
	{eng_current_pitch: 0},
	{target_p: 0},
	{min_pitch: 0},
	{max_pitch: 0},
	{bike_max_volume: 0},
	{bike_min_volume: 0},
	{bike_fade_start_dist: 0},
	{bike_volume_off_distance: 0},
	{bike_current_vol: 0},
	{bike_start_x: 0},
	{road_start_y: 0},
	{road_offset: 0},
	{is_checked: 0},
	{is_pause: 0},
	{trash_menu_opened: 0},
	{obj_timescale: 0},
	{block_top_buttons: 0},
	{trash_progress: 0},
	{levell: 0},
	{stagee: 0},
	{is_block: 0},
	{scroll_stage: 0},
	{scroll_y: 0},
	{kb_text: 0},
	{kb_mode: 0},
	{kb_opened: 0},
	{start_text: 0},
	{mode: 0},
	{description_key: 0},
	{name: 0},
	{w: 0},
	{anglee: 0},
	{code: 0},
	{map_data_json: 0},
	{obj_data: 0},
	{obj: 0},
	{is_valid: 0},
	{my_map_options_menu: 0},
	{came_from_my_maps_menu: 0},
	{touch_block: 0},
	{end_text_step: 0},
	{end_text_block: 0},
	{deaths_threshold: 0},
	{write_speed: 0},
	{txt: 0},
	{gameplay_state: 0},
	{game_started: 0},
	{first_gameplay_start_send: 0},
	{player_device: 0},
	{start_check_device: 0},
	{device: 0},
	{last_checkpoint_id: 0},
	{start_distance_to_finish: 0},
	{cur_distance: 0},
	{road_last_layout: 0},
	{farest_finish_uid: 0}
];

self.InstanceType = {
	pl: class extends self.ISpriteInstance {},
	pl_c: class extends self.ISpriteInstance {},
	pl_t: class extends self.ISpriteInstance {},
	finish: class extends self.ISpriteInstance {},
	slis: class extends self.ITiledBackgroundInstance {},
	space: class extends self.ITiledBackgroundInstance {},
	spd_bst: class extends self.ITiledBackgroundInstance {},
	in_game_button: class extends self.ISpriteInstance {},
	trigger_zone: class extends self.ISpriteInstance {},
	ice: class extends self.ITiledBackgroundInstance {},
	batut: class extends self.ISpriteInstance {},
	strelka: class extends self.ISpriteInstance {},
	checkpoint: class extends self.ISpriteInstance {},
	mn: class extends self.ISpriteInstance {},
	spk: class extends self.ITiledBackgroundInstance {},
	bow: class extends self.ISpriteInstance {},
	roll_s: class extends self.ISpriteInstance {},
	saw: class extends self.ISpriteInstance {},
	bike: class extends self.ISpriteInstance {},
	wheel: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	camera: class extends self.ISpriteInstance {},
	connector: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	sitelock: class extends self.IArrayInstance {},
	head: class extends self.ISpriteInstance {},
	leg: class extends self.ISpriteInstance {},
	body_top: class extends self.ISpriteInstance {},
	arm_: class extends self.ISpriteInstance {},
	arm: class extends self.ISpriteInstance {},
	leg_: class extends self.ISpriteInstance {},
	joint_to_bike_point: class extends self.ISpriteInstance {},
	Particles_wheel: class extends self.IParticlesInstance {},
	Particles_head: class extends self.IParticlesInstance {},
	test_text: class extends self.ITextInstance {},
	fon1: class extends self.ITiledBackgroundInstance {},
	top_button: class extends self.ISpriteInstance {},
	player_spawner: class extends self.ISpriteInstance {},
	editor_corner_changer: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	map_data: class extends self.IArrayInstance {},
	JSON: class extends self.IJSONInstance {},
	editor_obj_saver: class extends self.IDictionaryInstance {},
	editor_selecor: class extends self.ITiledBackgroundInstance {},
	editor_angle_changer: class extends self.ISpriteInstance {},
	editor_menu_fon: class extends self.ISpriteInstance {},
	build_menu_box: class extends self.ISpriteInstance {},
	editor_obj_ava: class extends self.ISpriteInstance {},
	editor_trash: class extends self.ISpriteInstance {},
	editor_menu_buttons: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	particles_explosion: class extends self.IParticlesInstance {},
	particles_explosion_smoke: class extends self.IParticlesInstance {},
	Audio: class extends self.IInstance {},
	raycast: class extends self.ISpriteInstance {},
	sound_pool: class extends self.IArrayInstance {},
	hat: class extends self.ISpriteInstance {},
	map_ava: class extends self.ISpriteInstance {},
	confetty: class extends self.ISpriteInstance {},
	particles_confetty: class extends self.IParticlesInstance {},
	mobile_control_buttons: class extends self.ISpriteInstance {},
	button: class extends self.ISpriteInstance {},
	text: class extends self.ISpriteFontInstance {},
	editor_side_changer: class extends self.ISpriteInstance {},
	editor_menu_page: class extends self.ISpriteInstance {},
	editor_menu_page_logos: class extends self.ISpriteInstance {},
	editor_menu_listat: class extends self.ISpriteInstance {},
	localization: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	Internationalization: class extends self.IInstance {},
	color_rect: class extends self.ISpriteInstance {},
	pers_logo: class extends self.ISpriteInstance {},
	tutor_buttons: class extends self.ISpriteInstance {},
	loading_sprite: class extends self.ISpriteInstance {},
	pause_fon: class extends self.ISpriteInstance {},
	pause_buttons: class extends self.ISpriteInstance {},
	pause_levels_asset: class extends self.ISpriteInstance {},
	listatt: class extends self.ISpriteInstance {},
	opened_levels: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	save_data: class extends self.IDictionaryInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Clipboard: class extends self.IInstance {},
	kb_enter: class extends self.ISpriteInstance {},
	my_maps_button: class extends self.ISpriteInstance {},
	my_maps_listat: class extends self.ISpriteInstance {},
	listat: class extends self.ISpriteInstance {},
	my_maps: class extends self.IArrayInstance {},
	message: class extends self.ISpriteInstance {},
	_9patch: class extends self.I9PatchInstance {},
	CSV: class extends self.IInstance {},
	PokiSDK: class extends C3.Plugins.skymen_pokiSDK.Instance {},
	bike_fixing_bug: class extends self.ISpriteInstance {},
	particles_confetty_flag: class extends self.IParticlesInstance {},
	PlatformInfo: class extends self.IInstance {},
	tutor_hand: class extends self.ISpriteInstance {},
	road_ui: class extends self.ISpriteInstance {},
	road_ui_head: class extends self.ISpriteInstance {},
	autoflip_zone: class extends self.ISpriteInstance {},
	body: class extends self.ISpriteInstance {},
	kill_zones: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	platforms: class extends self.ISpriteInstance {},
	level_obj: class extends self.ISpriteInstance {},
	level_obj_tiled: class extends self.ITiledBackgroundInstance {},
	editor_menu: class extends self.ISpriteInstance {},
	listats: class extends self.ISpriteInstance {},
	fons: class extends self.ITiledBackgroundInstance {},
	loading_spr: class extends self.ISpriteInstance {},
	menu_buttons: class extends self.ISpriteInstance {},
	pause_level_asset_clone: class extends self.ISpriteInstance {},
	checkpointt: class extends self.ISpriteInstance {}
}