const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Behaviors.Flash,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.skymen_pokiSDK,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.AJAX,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Plugins.Camera3D,
		C3.Plugins.Timeline,
		C3.Plugins.Dictionary,
		C3.Plugins.Arr,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.Shape3D,
		C3.Plugins.TiledBg,
		C3.Behaviors.Persist,
		C3.Behaviors.Bullet,
		C3.Behaviors.MoveTo,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Timer,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.JavaScriptInEvents.Loadingevt_Event3_Act1,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnError,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Shape3D.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Shape3D.Exps.ZHeight,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Shape3D.Acts.SetPos,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Camera3D.Exps.CameraZ,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Shape3D.Exps.Width,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Shape3D.Exps.TagAt,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Shape3D.Acts.SetFaceObject,
		C3.Plugins.Shape3D.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Shape3D.Cnds.HasTags,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Shape3D.Exps.FaceImagePointX,
		C3.Plugins.Shape3D.Exps.FaceImagePointY,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Shape3D.Acts.ChangeTags,
		C3.Plugins.Shape3D.Acts.AddChild,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Shape3D.Acts.SetFaceVisible,
		C3.Plugins.Shape3D.Acts.SetX,
		C3.Plugins.Shape3D.Acts.SetWidth,
		C3.Plugins.Shape3D.Acts.SetZHeight,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.System.Acts.SetFullscreenQuality,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Shape3D.Cnds.OnCreated,
		C3.Plugins.Shape3D.Exps.ParentUID,
		C3.Plugins.Shape3D.Exps.UID,
		C3.Plugins.Shape3D.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Shape3D.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Shape3D.Acts.AddInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Shape3D.Cnds.CompareZElevation,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Shape3D.Acts.SetBoolInstanceVar,
		C3.Plugins.Shape3D.Acts.RemoveFromParent,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Shape3D.Acts.SetY,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Shape3D.Cnds.CompareY,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.skymen_pokiSDK.Acts.Interstitial,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Timeline.Cnds.IsPlayingByTags,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.System.Exps.float,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Shape3D.Acts.SetEffectEnabled,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Timeline.Cnds.OnKeyframeReached,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Shape3D.Acts.SetPosToObject,
		C3.Plugins.System.Acts.StopLoop,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Shape3D.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Shape3D.Exps.PickedCount,
		C3.Behaviors.MoveTo.Acts.SetDeceleration,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Plugins.Camera3D.Exps.LookY,
		C3.Plugins.Camera3D.Exps.LookZ,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Acts.Sort2,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Plugins.Shape3D.Cnds.PickDistance,
		C3.Plugins.Shape3D.Exps.FaceImagePointZ,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Spritefont2.Exps.TagAt,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Spritefont2.Acts.SetEffectEnabled,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.ChangeTags,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Spritefont2.Exps.Tags,
		C3.Plugins.Camera3D.Exps.LookX,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Exps.layerindex,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.skymen_pokiSDK.Acts.Rewarded,
		C3.Plugins.skymen_pokiSDK.Cnds.LastRewardedSuccess,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.TagAt,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.skymen_pokiSDK.Acts.GameplayStop,
		C3.Plugins.skymen_pokiSDK.Acts.GameplayStart,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.Camera3D.Acts.SetFieldOfView,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Spritefont2.Acts.SetPosToObject
	];
};
self.C3_JsPropNameTable = [
	{species: 0},
	{Pin: 0},
	{TextGG: 0},
	{Text2: 0},
	{id: 0},
	{type: 0},
	{panel: 0},
	{Flash: 0},
	{Sine: 0},
	{mainText: 0},
	{id_2: 0},
	{svrha: 0},
	{purpose: 0},
	{Fade: 0},
	{SpriteFontMy: 0},
	{spriteFontBig: 0},
	{class: 0},
	{picked: 0},
	{res: 0},
	{touchEnabled: 0},
	{startY: 0},
	{subclass: 0},
	{button: 0},
	{temp: 0},
	{Tween: 0},
	{uniThumb: 0},
	{origWidth: 0},
	{origHeight: 0},
	{subtype: 0},
	{itemStyle: 0},
	{cena: 0},
	{uniButton: 0},
	{PokiSDK2: 0},
	{Touch: 0},
	{Browser: 0},
	{AJAX: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{Mouse: 0},
	{group: 0},
	{change: 0},
	{ButtonX: 0},
	{Keyboard: 0},
	{"3DCamera": 0},
	{TimelineController: 0},
	{StorageData: 0},
	{transitionMask: 0},
	{partnerLogo: 0},
	{gameText: 0},
	{arrTemp: 0},
	{arrUgaoFilderLetLopte: 0},
	{arrOsvojeneBazeFlat: 0},
	{arrLevels: 0},
	{Rotate: 0},
	{hourglass: 0},
	{levelCompleted: 0},
	{levelFailed: 0},
	{missed: 0},
	{ButtonTest: 0},
	{id2: 0},
	{iconBestScore: 0},
	{iconPoints: 0},
	{iconPointsSmall: 0},
	{ikonicaUni: 0},
	{iconCheckmark: 0},
	{pointid: 0},
	{timeToShowUp: 0},
	{tempX: 0},
	{tempY: 0},
	{desnjak: 0},
	{Sine0: 0},
	{Sine1: 0},
	{hand: 0},
	{hintPointer: 0},
	{SpriteNebo: 0},
	{"3DShape_Reflektor": 0},
	{TiledTribina: 0},
	{TiledFrontTribine: 0},
	{TiledTribina2: 0},
	{TiledGround: 0},
	{Persist: 0},
	{TiledOgrada: 0},
	{TiledReflektor: 0},
	{TiledOkolina_Komplet: 0},
	{Particles0: 0},
	{Particles2: 0},
	{Particles3: 0},
	{Particles4: 0},
	{Particles1: 0},
	{udaracParticles: 0},
	{"3DHomerunParticle": 0},
	{Scale: 0},
	{Bullet: 0},
	{Sine2: 0},
	{Konfetti: 0},
	{gameLogo: 0},
	{pageIndicator: 0},
	{panelBckg: 0},
	{stripeWinOrLose: 0},
	{surroundingsMask: 0},
	{flat_filder_1: 0},
	{flat_filder_2: 0},
	{flat_pitcher: 0},
	{ruka_1: 0},
	{ruka_2: 0},
	{ruka_3: 0},
	{rukavica_otvorena: 0},
	{rukavica_zatvorena: 0},
	{hiter_1: 0},
	{hiter_2: 0},
	{hiter_3: 0},
	{hiter_4: 0},
	{hiter_5: 0},
	{hiter_6: 0},
	{hiter_7: 0},
	{stopaloStrana: 0},
	{stopaloFront: 0},
	{palica: 0},
	{stopaloDignuto: 0},
	{flat_smetalo: 0},
	{loptaSenka: 0},
	{Text: 0},
	{holder: 0},
	{lopta_sprajt: 0},
	{nebeskoTelo: 0},
	{emojiPalica: 0},
	{lopta_crazy_sprajt: 0},
	{eksplozija_sprajt: 0},
	{"3DShapeTribina": 0},
	{"3DShapeKrov": 0},
	{"3DShapeOgrada": 0},
	{"3dShapeGround": 0},
	{"3DShapeReflektor": 0},
	{TravaDole: 0},
	{TravaGore: 0},
	{MoveTo: 0},
	{pivotKamere3DSh: 0},
	{PivotTerena: 0},
	{PivotStadiona: 0},
	{markerLeta: 0},
	{"3dShapeSemaforOsnova": 0},
	{"3dSemaforNatpis": 0},
	{semaforText_domacin: 0},
	{semaforText_gost: 0},
	{semaforText_crtica: 0},
	{semaforText_lvl10: 0},
	{semaforSimbolHitera: 0},
	{semaforText_lvl01: 0},
	{pitcherRazmislja3Dsh: 0},
	{pitcherSpichBabl: 0},
	{pitcherovPlan: 0},
	{pocX: 0},
	{pocY: 0},
	{zElevationMy: 0},
	{zVelocity: 0},
	{pitchnuta: 0},
	{udarena: 0},
	{uhvacena: 0},
	{dobacenaPitcheru: 0},
	{koDrziLoptuID: 0},
	{homerun: 0},
	{loptaCrazy3DSh: 0},
	{senkaCrazyLopte3Dsh: 0},
	{baza: 0},
	{timID: 0},
	{izgled: 0},
	{igrac3Dsh: 0},
	{lopta3DSh: 0},
	{Ax: 0},
	{Ay: 0},
	{pocAngle: 0},
	{hladjenjePosleUdarca: 0},
	{palica3DSh: 0},
	{repLopte3Dsh: 0},
	{horizInitCycle: 0},
	{zInitCycle: 0},
	{SineX: 0},
	{SineZ: 0},
	{noga3Dsh: 0},
	{rukavica3Dsh: 0},
	{desnaSaka3Dsh: 0},
	{levaSaka3Dsh: 0},
	{senkaIgraca3Dsh: 0},
	{smetalo3Dsh: 0},
	{nebeskoTelo3Dsh: 0},
	{emojiPalica3Dsh: 0},
	{strelica3DSh: 0},
	{senkaLopte3Dsh: 0},
	{eksplozija3DSh: 0},
	{fpsText: 0},
	{indNapretkaPodloga: 0},
	{indNapretkaTrofej: 0},
	{DragDrop: 0},
	{indNapretkaPoint: 0},
	{indNapretkaCrta: 0},
	{confettiFamily: 0},
	{Timer: 0},
	{Buttons: 0},
	{Icons: 0},
	{Tekstovi: 0},
	{stadion: 0},
	{igraci3dShapeFam: 0},
	{semaforTekst: 0},
	{loading_complete: 0},
	{initCounter: 0},
	{fejkGravitacija: 0},
	{centarX: 0},
	{centarY: 0},
	{homeY: 0},
	{poluprecnikTerena: 0},
	{udaljenostHomeRun: 0},
	{CameraX_poc: 0},
	{CameraZ_poc: 0},
	{CameraY_poc: 0},
	{cameraLookAtZ_poc: 0},
	{maxBrStrikeova: 0},
	{aktuelniStrikeovi: 0},
	{redBrUdarca: 0},
	{tempResultCPU: 0},
	{brojRanovaUOvojAkciji: 0},
	{tempResultPlayer: 0},
	{tutorijalOdgledan: 0},
	{akcijaJeGotova: 0},
	{trenutakZamaha: 0},
	{trenutakUdarca: 0},
	{cupsWon: 0},
	{crazyInning: 0},
	{pointsCurrent: 0},
	{pointsTop: 0},
	{kolikoSeDobijaPoena: 0},
	{maksBrojHitera: 0},
	{izgledTrenutnogHitera: 0},
	{nebo: 0},
	{boja: 0},
	{r: 0},
	{g: 0},
	{b: 0},
	{yOff: 0},
	{osnUrl: 0},
	{oznProtivnika: 0},
	{tempImgPoint: 0},
	{izgledLoc: 0},
	{tTween: 0},
	{faktorOdbitka: 0},
	{odlukaOPitchu: 0},
	{brojacPitcherovogPlana: 0},
	{sansaZaStrelu: 0},
	{slucBroj: 0},
	{udaljenostOdPitchera: 0},
	{tapnuoVidljivoDugme: 0},
	{zrtvaX: 0},
	{zrtvaY: 0},
	{sansaZaPojavuSmetala: 0},
	{cekanje: 0},
	{daLiDaSeSmetaloPojavi: 0},
	{nacinPojavljivanjaSmetala: 0},
	{nazivSmetala: 0},
	{randT: 0},
	{fejdLopte: 0},
	{noviUgaoLetaLopte: 0},
	{tabelaUglova: 0},
	{tabelaUglova2: 0},
	{tTabelarno: 0},
	{ugao2: 0},
	{ugao1: 0},
	{procenat: 0},
	{homerunTmin: 0},
	{homerunTmax: 0},
	{extraBrzina: 0},
	{fielderUID: 0},
	{tempText: 0},
	{kolikoNjihTrci: 0},
	{brOsvojenihBaza: 0},
	{komentar: 0},
	{igracUID: 0},
	{lerpFaktor: 0},
	{pivotKamereTrenutnoX: 0},
	{pivotKamereTrenutnoY: 0},
	{pivotKamerePlaniranoX: 0},
	{pivotKamerePlaniranoY: 0},
	{ciljZaPracenjeX: 0},
	{ciljZaPracenjeY: 0},
	{jelSmeDaHvata: 0},
	{podnaslov: 0},
	{endPoruka: 0},
	{kolikoParticla: 0},
	{krajMeca: 0},
	{pobeda: 0},
	{naslov: 0},
	{zaustaviAkciju: 0},
	{parentUID: 0},
	{brojNivoa: 0},
	{LANGUAGE_ID: 0},
	{locStorageNameBase: 0},
	{LEVEL: 0},
	{LAST_LEVEL: 0},
	{rewardReklamaSvrha: 0},
	{ourTeamStyleID: 0},
	{tPisanja: 0},
	{fieldTag: 0},
	{valueToWrite: 0},
	{typeWrite: 0},
	{skaliraj: 0},
	{layersToShow: 0},
	{panelTopText: 0},
	{pauziraj: 0},
	{buttonUID: 0},
	{svrhaRewardReklame: 0},
	{SOUND_STATUS: 0},
	{MUSIC_STATUS: 0},
	{musicVolume: 0},
	{soundVolume: 0},
	{muzickiTagovi: 0},
	{POKI_GAMEPLAY_STOPPED: 0},
	{widthLandscape: 0},
	{heightLandscape: 0}
];

self.InstanceType = {
	TextGG: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	mainText: class extends self.ITextInstance {},
	SpriteFontMy: class extends self.ISpriteFontInstance {},
	spriteFontBig: class extends self.ISpriteFontInstance {},
	button: class extends self.ISpriteInstance {},
	uniThumb: class extends self.ISpriteInstance {},
	uniButton: class extends self.ISpriteInstance {},
	PokiSDK2: class extends C3.Plugins.skymen_pokiSDK.Instance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	ButtonX: class extends self.IButtonInstance {},
	Keyboard: class extends self.IInstance {},
	_3DCamera: class extends self.IInstance {},
	TimelineController: class extends self.IInstance {},
	StorageData: class extends self.IDictionaryInstance {},
	transitionMask: class extends self.ISpriteInstance {},
	partnerLogo: class extends self.ISpriteInstance {},
	gameText: class extends self.IArrayInstance {},
	arrTemp: class extends self.IArrayInstance {},
	arrUgaoFilderLetLopte: class extends self.IArrayInstance {},
	arrOsvojeneBazeFlat: class extends self.IArrayInstance {},
	arrLevels: class extends self.IArrayInstance {},
	hourglass: class extends self.ISpriteInstance {},
	levelCompleted: class extends self.IButtonInstance {},
	levelFailed: class extends self.IButtonInstance {},
	missed: class extends self.IButtonInstance {},
	ButtonTest: class extends self.IButtonInstance {},
	iconBestScore: class extends self.ISpriteInstance {},
	iconPoints: class extends self.ISpriteInstance {},
	iconPointsSmall: class extends self.IParticlesInstance {},
	ikonicaUni: class extends self.ISpriteInstance {},
	iconCheckmark: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	hintPointer: class extends self.ISpriteInstance {},
	SpriteNebo: class extends self.ISpriteInstance {},
	_3DShape_Reflektor: class extends self.I3DShapeInstance {},
	TiledTribina: class extends self.ITiledBackgroundInstance {},
	TiledFrontTribine: class extends self.ITiledBackgroundInstance {},
	TiledTribina2: class extends self.ITiledBackgroundInstance {},
	TiledGround: class extends self.ITiledBackgroundInstance {},
	TiledOgrada: class extends self.ITiledBackgroundInstance {},
	TiledReflektor: class extends self.ITiledBackgroundInstance {},
	TiledOkolina_Komplet: class extends self.ITiledBackgroundInstance {},
	Particles0: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Particles4: class extends self.IParticlesInstance {},
	Particles1: class extends self.IParticlesInstance {},
	udaracParticles: class extends self.IParticlesInstance {},
	_3DHomerunParticle: class extends self.I3DShapeInstance {},
	Konfetti: class extends self.ISpriteInstance {},
	gameLogo: class extends self.ISpriteInstance {},
	pageIndicator: class extends self.ISpriteInstance {},
	panelBckg: class extends self.ISpriteInstance {},
	stripeWinOrLose: class extends self.ISpriteInstance {},
	surroundingsMask: class extends self.ISpriteInstance {},
	flat_filder_1: class extends self.ISpriteInstance {},
	flat_filder_2: class extends self.ISpriteInstance {},
	flat_pitcher: class extends self.ISpriteInstance {},
	ruka_1: class extends self.ISpriteInstance {},
	ruka_2: class extends self.ISpriteInstance {},
	ruka_3: class extends self.ISpriteInstance {},
	rukavica_otvorena: class extends self.ISpriteInstance {},
	rukavica_zatvorena: class extends self.ISpriteInstance {},
	hiter_1: class extends self.ISpriteInstance {},
	hiter_2: class extends self.ISpriteInstance {},
	hiter_3: class extends self.ISpriteInstance {},
	hiter_4: class extends self.ISpriteInstance {},
	hiter_5: class extends self.ISpriteInstance {},
	hiter_6: class extends self.ISpriteInstance {},
	hiter_7: class extends self.ISpriteInstance {},
	stopaloStrana: class extends self.ISpriteInstance {},
	stopaloFront: class extends self.ISpriteInstance {},
	palica: class extends self.ISpriteInstance {},
	stopaloDignuto: class extends self.ISpriteInstance {},
	flat_smetalo: class extends self.ISpriteInstance {},
	loptaSenka: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	holder: class extends self.ISpriteInstance {},
	lopta_sprajt: class extends self.ISpriteInstance {},
	nebeskoTelo: class extends self.ISpriteInstance {},
	emojiPalica: class extends self.ISpriteInstance {},
	lopta_crazy_sprajt: class extends self.ISpriteInstance {},
	eksplozija_sprajt: class extends self.ISpriteInstance {},
	_3DShapeTribina: class extends self.I3DShapeInstance {},
	_3DShapeKrov: class extends self.I3DShapeInstance {},
	_3DShapeOgrada: class extends self.I3DShapeInstance {},
	_3dShapeGround: class extends self.I3DShapeInstance {},
	_3DShapeReflektor: class extends self.I3DShapeInstance {},
	TravaDole: class extends self.ISpriteInstance {},
	TravaGore: class extends self.ISpriteInstance {},
	pivotKamere3DSh: class extends self.I3DShapeInstance {},
	PivotTerena: class extends self.I3DShapeInstance {},
	PivotStadiona: class extends self.I3DShapeInstance {},
	markerLeta: class extends self.ISpriteInstance {},
	_3dShapeSemaforOsnova: class extends self.I3DShapeInstance {},
	_3dSemaforNatpis: class extends self.I3DShapeInstance {},
	semaforText_domacin: class extends self.ISpriteInstance {},
	semaforText_gost: class extends self.ISpriteInstance {},
	semaforText_crtica: class extends self.ISpriteInstance {},
	semaforText_lvl10: class extends self.ISpriteInstance {},
	semaforSimbolHitera: class extends self.ISpriteInstance {},
	semaforText_lvl01: class extends self.ISpriteInstance {},
	pitcherRazmislja3Dsh: class extends self.I3DShapeInstance {},
	pitcherSpichBabl: class extends self.I3DShapeInstance {},
	pitcherovPlan: class extends self.ISpriteInstance {},
	loptaCrazy3DSh: class extends self.I3DShapeInstance {},
	senkaCrazyLopte3Dsh: class extends self.I3DShapeInstance {},
	igrac3Dsh: class extends self.I3DShapeInstance {},
	lopta3DSh: class extends self.I3DShapeInstance {},
	palica3DSh: class extends self.I3DShapeInstance {},
	repLopte3Dsh: class extends self.I3DShapeInstance {},
	noga3Dsh: class extends self.I3DShapeInstance {},
	rukavica3Dsh: class extends self.I3DShapeInstance {},
	desnaSaka3Dsh: class extends self.I3DShapeInstance {},
	levaSaka3Dsh: class extends self.I3DShapeInstance {},
	senkaIgraca3Dsh: class extends self.I3DShapeInstance {},
	smetalo3Dsh: class extends self.I3DShapeInstance {},
	nebeskoTelo3Dsh: class extends self.I3DShapeInstance {},
	emojiPalica3Dsh: class extends self.I3DShapeInstance {},
	strelica3DSh: class extends self.I3DShapeInstance {},
	senkaLopte3Dsh: class extends self.I3DShapeInstance {},
	eksplozija3DSh: class extends self.I3DShapeInstance {},
	fpsText: class extends self.ITextInstance {},
	indNapretkaPodloga: class extends self.ISpriteInstance {},
	indNapretkaTrofej: class extends self.ISpriteInstance {},
	indNapretkaPoint: class extends self.ISpriteInstance {},
	indNapretkaCrta: class extends self.ISpriteInstance {},
	confettiFamily: class extends self.IParticlesInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Icons: class extends self.ISpriteInstance {},
	Tekstovi: class extends self.ISpriteFontInstance {},
	stadion: class extends self.I3DShapeInstance {},
	igraci3dShapeFam: class extends self.I3DShapeInstance {},
	semaforTekst: class extends self.ISpriteInstance {}
}