const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.Json,
		C3.Plugins.AJAX,
		C3.Plugins.skymen_pokiSDK,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Behaviors.Timer,
		C3.Behaviors.Physics,
		C3.Behaviors.LOS,
		C3.Plugins.Particles,
		C3.Behaviors.Follow,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.scrollto,
		C3.Behaviors.Anchor,
		C3.Plugins.NinePatch,
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetSteppingMode,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Physics.Acts.ApplyForce,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Behaviors.LOS.Acts.CastRay,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Behaviors.LOS.Cnds.RayIntersected,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.LOS.Exps.NormalAngle,
		C3.JavaScriptInEvents.Game_Event42_Act3,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetPreventRotate,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Behaviors.LOS.Exps.HitX,
		C3.Behaviors.LOS.Exps.HitY,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Particles.Acts.SetInitSpeed,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Acts.SetDefaultColor,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Tween.Acts.SetTweensTime,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Behaviors.Physics.Exps.Density,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Follow.Cnds.IsFollowingObject,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.LayerNameExists,
		C3.Plugins.System.Acts.AddLayer,
		C3.Plugins.DrawingCanvas.Acts.SetSize,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.JavaScriptInEvents.Game_Event107_Act1,
		C3.Plugins.DrawingCanvas.Acts.FillEllipse,
		C3.JavaScriptInEvents.Game_Event109_Act1,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.JavaScriptInEvents.Game_Event110_Act1,
		C3.JavaScriptInEvents.Game_Event111_Act1,
		C3.Plugins.System.Acts.SetLayoutAngle,
		C3.Plugins.System.Acts.SetLayerAngle,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.TiledBg.Acts.MoveAtAngle,
		C3.Plugins.TiledBg.Exps.Angle,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Acts.SetLayerBlendMode,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.TiledBg.Acts.SetImageScaleY,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.NinePatch.Exps.BBoxMidX,
		C3.Plugins.NinePatch.Exps.BBoxMidY,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.NinePatch.Cnds.OnCreated,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Exps.Angle,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Text.Acts.SetAngle,
		C3.Plugins.System.Exps.tokenat,
		C3.JavaScriptInEvents.Game_Event129_Act10,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetFramerateMode,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Cnds.OnHierarchyReady,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Exps.TemplateName,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.JavaScriptInEvents.Game_Event169_Act3,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Behaviors.Physics.Cnds.IsImmovable,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Cnds.HasParent,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Cnds.PickParent,
		C3.Behaviors.Physics.Acts.CreateDistanceJoint,
		C3.Plugins.Sprite.Cnds.HasParent,
		C3.Plugins.System.Exps.layoutangle,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.TiledBg.Exps.BBoxTop,
		C3.Behaviors.Physics.Acts.SetFriction,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Physics.Acts.Teleport,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Browser.Exps.Language,
		C3.JavaScriptInEvents.Loader_Event2_Act5,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.JavaScriptInEvents.Loader_Event7_Act2,
		C3.Plugins.System.Exps.loadingprogress,
		C3.JavaScriptInEvents.Loader_Event8_Act1,
		C3.JavaScriptInEvents.General_Event2_Act1,
		C3.JavaScriptInEvents.General_Event4_Act1,
		C3.JavaScriptInEvents.General_Event5_Act1,
		C3.Plugins.skymen_pokiSDK.Acts.GameplayStart,
		C3.Plugins.skymen_pokiSDK.Acts.GameplayStop,
		C3.Plugins.skymen_pokiSDK.Acts.Interstitial
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{loading_percent: 0},
	{language: 0},
	{colors: 0},
	{AJAX: 0},
	{PokiSDK: 0},
	{Keyboard: 0},
	{Browser: 0},
	{Touch: 0},
	{PlatformInfo: 0},
	{Audio: 0},
	{Mouse: 0},
	{acceleration: 0},
	{deceleration: 0},
	{max_speed: 0},
	{jump_strength: 0},
	{gravity: 0},
	{coyote: 0},
	{prevent_rotation: 0},
	{landed: 0},
	{gravity_reversed: 0},
	{slide: 0},
	{motor: 0},
	{moving: 0},
	{screenwrap: 0},
	{Timer: 0},
	{Physics: 0},
	{LineOfSight: 0},
	{player: 0},
	{vX: 0},
	{vY: 0},
	{player_face: 0},
	{player_los: 0},
	{player_particles: 0},
	{player_death_particles: 0},
	{player_shadow: 0},
	{Follow: 0},
	{mooncoin: 0},
	{player_hat: 0},
	{signal_receiver: 0},
	{tween_dir_factor: 0},
	{tween_extra: 0},
	{tween_duration_override: 0},
	{Solid: 0},
	{tiled_solid: 0},
	{outside_solid: 0},
	{Sine: 0},
	{Sine2: 0},
	{solid_anchor: 0},
	{round_solid: 0},
	{curr_direct: 0},
	{ScrollTo: 0},
	{camera: 0},
	{offset_X: 0},
	{offset_Y: 0},
	{priority: 0},
	{camera_director: 0},
	{init_w: 0},
	{init_h: 0},
	{dir: 0},
	{button_move: 0},
	{button_jump: 0},
	{Anchor: 0},
	{ctrl_anchor: 0},
	{button_reset: 0},
	{button_sprite: 0},
	{button_restart: 0},
	{goal_door: 0},
	{goal_extra: 0},
	{tutorial: 0},
	{str: 0},
	{tutorial_text: 0},
	{tutorial_spawner: 0},
	{hint: 0},
	{r_button: 0},
	{hint_text: 0},
	{debug_dot: 0},
	{fps_counter: 0},
	{background_gradient: 0},
	{solid_gradient: 0},
	{DrawingCanvas: 0},
	{shape_fruit: 0},
	{gyro_fruit: 0},
	{Rotate: 0},
	{gyro_orbit: 0},
	{signal: 0},
	{function: 0},
	{audio: 0},
	{add_tag: 0},
	{button: 0},
	{button_press: 0},
	{grow_fruit_core: 0},
	{grow_fruit_arrow: 0},
	{buzzsaw: 0},
	{screenwrap_visual: 0},
	{level_progress: 0},
	{world_text: 0},
	{transition_player: 0},
	{transition_player_face: 0},
	{congrats_text: 0},
	{buttons: 0},
	{translated_text: 0},
	{signal_sprite: 0},
	{fruits: 0},
	{all_text: 0},
	{signal_receiver_sprite: 0},
	{current_world: 0},
	{current_level: 0},
	{restarting: 0},
	{player_base_size: 0},
	{grow_speed: 0},
	{fading_out: 0},
	{steepness: 0},
	{by: 0},
	{vX_limit: 0},
	{prevent: 0},
	{camera_speed_X: 0},
	{camera_speed_Y: 0},
	{camera_offset_Y: 0},
	{camera_offset_X: 0},
	{camera_offset_Y_portrait: 0},
	{value: 0},
	{max_face_distance: 0},
	{face_speed: 0},
	{stiffness: 0},
	{damping: 0},
	{face_speed3: 0},
	{target_X: 0},
	{target_Y: 0},
	{shadow_offset: 0},
	{slime_density: 0},
	{slime_steps: 0},
	{speed: 0},
	{density: 0},
	{image_size_factor: 0},
	{anim: 0},
	{w: 0},
	{h: 0},
	{crush_duration: 0},
	{r: 0},
	{g: 0},
	{b: 0},
	{x: 0},
	{y: 0},
	{color: 0},
	{radius: 0},
	{fade_duration: 0},
	{name: 0},
	{id: 0},
	{play_over: 0},
	{volume: 0},
	{shape: 0},
	{fruit_angle_offset: 0},
	{wiggle_speed: 0},
	{arrow_dist: 0},
	{grow: 0},
	{button_impulse: 0},
	{screenwrap_limit_Y: 0},
	{new_player: 0},
	{gameplay_started: 0}
];

self.InstanceType = {
	loading_percent: class extends self.ITextInstance {},
	language: class extends self.IJSONInstance {},
	colors: class extends self.IJSONInstance {},
	AJAX: class extends self.IInstance {},
	PokiSDK: class extends C3.Plugins.skymen_pokiSDK.Instance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	player: class extends self.ISpriteInstance {},
	player_face: class extends self.ISpriteInstance {},
	player_los: class extends self.ISpriteInstance {},
	player_particles: class extends self.IParticlesInstance {},
	player_death_particles: class extends self.IParticlesInstance {},
	player_shadow: class extends self.ISpriteInstance {},
	mooncoin: class extends self.ISpriteInstance {},
	player_hat: class extends self.ISpriteInstance {},
	tiled_solid: class extends self.ITiledBackgroundInstance {},
	outside_solid: class extends self.ITiledBackgroundInstance {},
	solid_anchor: class extends self.ISpriteInstance {},
	round_solid: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	camera_director: class extends self.ISpriteInstance {},
	button_move: class extends self.ISpriteInstance {},
	button_jump: class extends self.ISpriteInstance {},
	ctrl_anchor: class extends self.ISpriteInstance {},
	button_reset: class extends self.ISpriteInstance {},
	button_sprite: class extends self.ISpriteInstance {},
	button_restart: class extends self.ISpriteInstance {},
	goal_door: class extends self.I9PatchInstance {},
	goal_extra: class extends self.I9PatchInstance {},
	tutorial: class extends self.ISpriteInstance {},
	tutorial_text: class extends self.ITextInstance {},
	tutorial_spawner: class extends self.ISpriteInstance {},
	hint: class extends self.ISpriteInstance {},
	r_button: class extends self.ISpriteInstance {},
	hint_text: class extends self.ITextInstance {},
	debug_dot: class extends self.ISpriteInstance {},
	fps_counter: class extends self.ITextInstance {},
	background_gradient: class extends self.ITiledBackgroundInstance {},
	solid_gradient: class extends self.ITiledBackgroundInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	shape_fruit: class extends self.ISpriteInstance {},
	gyro_fruit: class extends self.ISpriteInstance {},
	gyro_orbit: class extends self.ISpriteInstance {},
	button: class extends self.ISpriteInstance {},
	button_press: class extends self.ISpriteInstance {},
	grow_fruit_core: class extends self.ISpriteInstance {},
	grow_fruit_arrow: class extends self.ISpriteInstance {},
	buzzsaw: class extends self.ISpriteInstance {},
	screenwrap_visual: class extends self.ITiledBackgroundInstance {},
	level_progress: class extends self.ISpriteInstance {},
	world_text: class extends self.ITextInstance {},
	transition_player: class extends self.ISpriteInstance {},
	transition_player_face: class extends self.ISpriteInstance {},
	congrats_text: class extends self.ITextInstance {},
	buttons: class extends self.ISpriteInstance {},
	translated_text: class extends self.ITextInstance {},
	signal_sprite: class extends self.ISpriteInstance {},
	fruits: class extends self.ISpriteInstance {},
	all_text: class extends self.ITextInstance {},
	signal_receiver_sprite: class extends self.ISpriteInstance {}
}