const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Tween,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Behaviors.Flash,
		C3.Plugins.skymen_pokiSDK,
		C3.Plugins.Particles,
		C3.Behaviors.scrollto,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Physics.Acts.CreateLimitedRevoluteJoint,
		C3.Behaviors.Physics.Acts.ApplyTorque,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Physics.Acts.ApplyImpulseToward,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Spritefont2.Acts.SetAngle,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Physics.Acts.SetCollisionFilter,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.MoveToLayer
	];
};
self.C3_JsPropNameTable = [
	{targetX: 0},
	{targetY: 0},
	{Physics: 0},
	{Pin: 0},
	{RightLegUp: 0},
	{LeftLegUp: 0},
	{LeftArmUp: 0},
	{RightArmUp: 0},
	{RightLegDown: 0},
	{LeftLegDown: 0},
	{RightArmDown: 0},
	{LeftArmDown: 0},
	{money: 0},
	{multilier: 0},
	{Body: 0},
	{Head: 0},
	{Touch: 0},
	{DebugText: 0},
	{Tween: 0},
	{SpriteFont: 0},
	{collider: 0},
	{Sprite4: 0},
	{PinPlace: 0},
	{selectedPin: 0},
	{canMerge: 0},
	{GameHandler: 0},
	{multiplier: 0},
	{multiplierCollider: 0},
	{cost: 0},
	{costMultiplier: 0},
	{ButtonAddNewPin: 0},
	{level: 0},
	{nextLevelAt: 0},
	{levelCounter: 0},
	{numberOfRagdoll: 0},
	{autoDrop: 0},
	{pinForce: 0},
	{finalMultiplier: 0},
	{Save: 0},
	{ButtonAddRagdoll: 0},
	{Sprite3: 0},
	{Mouse: 0},
	{Sprite12: 0},
	{StartHere: 0},
	{Sine: 0},
	{Sine2: 0},
	{TouchHereText: 0},
	{TextMoney: 0},
	{Flash: 0},
	{TextRagdolls: 0},
	{TextLevel: 0},
	{ButtonAutoDrop: 0},
	{ButtonFinalMultiplier: 0},
	{ButtonPinForce: 0},
	{TextButtonPrice: 0},
	{Sprite2: 0},
	{LevelYellow: 0},
	{LevelUpText: 0},
	{PokiSDK: 0},
	{Sprite: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{ParticlePinCreated: 0},
	{PinHitEffect: 0},
	{HandSprite: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{TextLevelUpMoney: 0},
	{PlayerFamily: 0},
	{MoveTo: 0},
	{PinFamily: 0},
	{Buttons: 0},
	{Outlines: 0},
	{moneyToAdd: 0}
];

self.InstanceType = {
	Pin: class extends self.ISpriteInstance {},
	RightLegUp: class extends self.ISpriteInstance {},
	LeftLegUp: class extends self.ISpriteInstance {},
	LeftArmUp: class extends self.ISpriteInstance {},
	RightArmUp: class extends self.ISpriteInstance {},
	RightLegDown: class extends self.ISpriteInstance {},
	LeftLegDown: class extends self.ISpriteInstance {},
	RightArmDown: class extends self.ISpriteInstance {},
	LeftArmDown: class extends self.ISpriteInstance {},
	Body: class extends self.ISpriteInstance {},
	Head: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	DebugText: class extends self.ITextInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	collider: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	PinPlace: class extends self.ISpriteInstance {},
	GameHandler: class extends self.ISpriteInstance {},
	multiplierCollider: class extends self.ISpriteInstance {},
	ButtonAddNewPin: class extends self.ISpriteInstance {},
	Save: class extends self.ISpriteInstance {},
	ButtonAddRagdoll: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	StartHere: class extends self.ITiledBackgroundInstance {},
	TouchHereText: class extends self.ISpriteInstance {},
	TextMoney: class extends self.ITextInstance {},
	TextRagdolls: class extends self.ITextInstance {},
	TextLevel: class extends self.ITextInstance {},
	ButtonAutoDrop: class extends self.ISpriteInstance {},
	ButtonFinalMultiplier: class extends self.ISpriteInstance {},
	ButtonPinForce: class extends self.ISpriteInstance {},
	TextButtonPrice: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	LevelYellow: class extends self.ISpriteInstance {},
	LevelUpText: class extends self.ISpriteInstance {},
	PokiSDK: class extends C3.Plugins.skymen_pokiSDK.Instance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	ParticlePinCreated: class extends self.IParticlesInstance {},
	PinHitEffect: class extends self.ISpriteInstance {},
	HandSprite: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	TextLevelUpMoney: class extends self.ITextInstance {},
	PlayerFamily: class extends self.ISpriteInstance {},
	PinFamily: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Outlines: class extends self.ISpriteInstance {}
}